import localFont from "next/font/local";
import "./globals.css";
import Navbar from '../components/Navbar'; 



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const Layout = ({ children }) => {
  return (
    <div>
      {/* Ajoutez la navbar ici */}
      <Navbar />
      
      {/* Le contenu de la page */}
      <main>{children}</main>
    </div>
  );
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
